version: "2"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ushahidi
      MYSQL_USER: ushahidi
      MYSQL_PASSWORD: ushahidi
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "33061:3306"
  redis:
    image: redis:4-alpine
  platform:
    build: .
    environment:
      APP_KEY: SomeRandomKey!!!SomeRandomKey!!!
      DOCKERIZE_TIMEOUT: 180s
      DOCKERIZE_WAIT_FOR_mysql: tcp://mysql:3306
      DOCKERIZE_WAIT_FOR_redis: tcp://redis:6379
      ENABLE_NGINX: "true"
      ENABLE_PHPFPM: "true"
      ENABLE_PLATFORM_TASKS: "false"
      RUN_PLATFORM_MIGRATIONS: "true"
      DB_CONNECTION: mysql
      DB_DATABASE: ushahidi
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: ushahidi
      DB_PASSWORD: ushahidi
      REDIS_HOST: redis
      CACHE_DRIVER: redis
      QUEUE_DRIVER: redis
    command: start
    ports:
      - "80:8080"
    volumes:
      - storage-app-public:/var/www/storage/app/public
      - ./:/vols/src
  platform_tasks:
    build: .
    environment:
      APP_KEY: SomeRandomKey!!!SomeRandomKey!!!
      DOCKERIZE_TIMEOUT: 180s
      DOCKERIZE_WAIT_FOR_mysql: tcp://mysql:3306
      DOCKERIZE_WAIT_FOR_redis: tcp://redis:6379
      ENABLE_NGINX: "false"
      ENABLE_PHPFPM: "false"
      ENABLE_PLATFORM_TASKS: "true"
      ENABLE_QUEUE_LISTEN: "true"
      TASK_RUN_PERIOD_SECS: "30"
      RUN_PLATFORM_MIGRATIONS: "false"
      DB_CONNECTION: mysql
      DB_DATABASE: ushahidi
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: ushahidi
      DB_PASSWORD: ushahidi
      REDIS_HOST: redis
      CACHE_DRIVER: redis
      QUEUE_DRIVER: redis
    command: start
    volumes:
      - storage-app-public:/var/www/storage/app/public

volumes:
  # share storage/app/public between platform containers
  storage-app-public:
